### ISSUE TITLE
Feature Request Show Notifications

### ISSUE THREAD

**Issue by Galthariel** [marticliment/Youtube-TV-Client#2]
I couldn't find it anywhere so there may be a way so I'm sorry in advance. Is there a way to show YouTube Notifications in the App?

**Comment by marticliment** [comment]
Hello @Galthariel, 

This app is a modified web wrapper for Youtube TV to run on, so not all the in-app features are available. I am afraid that if the notifications options are not already present in the already existing app, notifications are then not available.

**Comment by Galthariel** [comment]
thank you very much for your prompt reply and Merry Christmas
